# Generated by Django 6.0.5 on 2026-06-01 12:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Укажите название книги')),
                ('author', models.CharField(max_length=100, verbose_name='Укажите автора')),
                ('publication_year', models.IntegerField(verbose_name='Укажите год публикации')),
                ('photo', models.ImageField(upload_to='books_smth/', verbose_name='Загрузите фото книги')),
                ('genre', models.CharField(choices=[('Фантастика', 'Фантастика'), ('Детектив', 'Детектив'), ('Романтика', 'Романтика'), ('Проза', 'Проза'), ('Драма', 'Драма'), ('Психология', 'Психология')], max_length=100, verbose_name='Укажите жанр')),
                ('description', models.TextField(verbose_name='Укажите описание книги')),
                ('publisher', models.CharField(choices=[('Эксмо', 'Эксмо'), ('Издательство АСТ', 'Издательство АСТ'), ('РОСМЭН', 'РОСМЭН'), ('Азбука-Аттикус', 'Азбука-Аттикус'), ('Просвещение', 'Просвещение'), ('Image Comics', 'Image Comics')], max_length=100, verbose_name='укажите издательство')),
                ('pages', models.IntegerField(blank=True, null=True, verbose_name='Укажите количество страниц')),
                ('reserve_book', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Укажите количество книг для бронирования')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'книга',
                'verbose_name_plural': 'книги',
            },
        ),
    ]
