# Generated by Django 6.0.5 on 2026-06-06 16:00

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('photo', models.ImageField(upload_to='users/')),
                ('phone_number', models.CharField(max_length=15)),
                ('adress', models.CharField(default='Bishkek', max_length=200)),
                ('gender', models.CharField(default='m', max_length=100)),
                ('status', models.CharField(default='married', max_length=100)),
                ('kids', models.CharField(default='none', max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('salary', models.IntegerField(verbose_name='Ожидаемая зарплата?')),
                ('language', models.CharField(default='ru', max_length=100)),
                ('hire_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
