# Generated by Django 6.0.5 on 2026-06-11 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='views',
            field=models.PositiveIntegerField(db_default=0, null=True),
        ),
    ]
