# Generated by Django 6.0.5 on 2026-06-16 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CineBoard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('Фантастика', 'Фантастика'), ('Детектив', 'Детектив'), ('Романтика', 'Романтика'), ('Боевик', 'Боевик'), ('Драма', 'Драма'), ('Хорор', 'Хорор')], default='Драма', max_length=100),
        ),
    ]
