# Generated by Django 6.0.5 on 2026-06-16 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CineBoard', '0002_movie_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='genre',
        ),
        migrations.AddField(
            model_name='movie',
            name='language',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(choices=[('Фантастика', 'Фантастика'), ('Детектив', 'Детектив'), ('Романтика', 'Романтика'), ('Боевик', 'Боевик'), ('Драма', 'Драма'), ('Хорор', 'Хорор')], default='Драма', max_length=100),
        ),
    ]
