# Generated by Django 6.0.5 on 2026-06-16 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CineBoard', '0004_alter_genre_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(choices=[('Фантастика', 'Фантастика'), ('Детектив', 'Детектив'), ('Романтика', 'Романтика'), ('Боевик', 'Боевик'), ('Драма', 'Драма'), ('Хорор', 'Хорор')], default='Драма', max_length=100),
        ),
    ]
