# Generated by Django 6.0.5 on 2026-06-16 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CineBoard', '0005_alter_genre_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='auhtor',
            new_name='author',
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
