# Generated by Django 6.0.5 on 2026-06-16 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CineBoard', '0006_rename_auhtor_comment_author_alter_genre_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vip',
            name='seat_num',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
