# Generated by Django 6.0.5 on 2026-06-01 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horse_tour', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoiceHorse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horse_name', models.CharField(max_length=100)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='horse_tour.person')),
            ],
        ),
        migrations.DeleteModel(
            name='Horse',
        ),
    ]
