# Generated by Django 6.0.5 on 2026-06-01 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horse_tour', '0002_choicehorse_delete_horse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='horsetour',
            old_name='title',
            new_name='tittle',
        ),
    ]
