# Generated by Django 6.0.5 on 2026-06-11 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horse_tour', '0003_rename_title_horsetour_tittle'),
    ]

    operations = [
        migrations.AddField(
            model_name='horsetour',
            name='views',
            field=models.PositiveIntegerField(db_default=0, null=True),
        ),
    ]
