# Generated by Django 6.0.5 on 2026-06-11 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horse_tour', '0004_horsetour_views'),
    ]

    operations = [
        migrations.RenameField(
            model_name='horsetour',
            old_name='tittle',
            new_name='title',
        ),
    ]
