# Generated by Django 6.0.5 on 2026-06-04 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Thing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='укажите название товара')),
                ('photo', models.ImageField(upload_to='buy_things/', verbose_name='загрузите фото товара')),
                ('price', models.IntegerField(verbose_name='укажите цену товара')),
                ('description', models.TextField(verbose_name='укажите описание товара')),
                ('mark', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=100, verbose_name='оцените товар от 1-5')),
            ],
        ),
    ]
