# Generated by Django 6.0.5 on 2026-06-06 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BASKET', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thing',
            name='mark',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=100, verbose_name='оцените товар'),
        ),
    ]
